// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Uj49QYxK389Omq_nLQ2k_HJr9um6Z8k',
    appId: '1:800446631265:web:a3e3ea582b05076713c920',
    messagingSenderId: '800446631265',
    projectId: 'video-to-webp',
    authDomain: 'video-to-webp.firebaseapp.com',
    storageBucket: 'video-to-webp.firebasestorage.app',
    measurementId: 'G-YE9QH3S5X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYdBvdjfuWaIu9FRS2eJz8B8K3R_yzNs',
    appId: '1:800446631265:android:eb5f288c13ff7a8d13c920',
    messagingSenderId: '800446631265',
    projectId: 'video-to-webp',
    storageBucket: 'video-to-webp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBeiC8YlCzln9ZfvaiBzqxFe54OWOJgjU',
    appId: '1:800446631265:ios:f30e91c83833387313c920',
    messagingSenderId: '800446631265',
    projectId: 'video-to-webp',
    storageBucket: 'video-to-webp.firebasestorage.app',
    iosBundleId: 'com.jylee.videoToWebp',
  );
}
